trigger:
- main  # Branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'  # Specify your Python version
    addToPath: true

- checkout: self

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover  # Adjust this line if you're using a different test framework
  displayName: 'Run unit tests'

- script: |
    python -m flake8 .  # Run linter (flake8) to check for style issues
  displayName: 'Run linter'
