# Generated by Django 3.0.8 on 2024-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchstock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.AddField(
            model_name='profile',
            name='userRole',
            field=models.CharField(choices=[('Higher Approver', 'Higher Approver'), ('Order Manager', 'Order Manager'), ('Stock Manager', 'Stock Manager'), ('Supervisor', 'Supervisor'), ('Research Staff Member', 'Research Staff Member'), ('Admin', 'Admin')], default='Research Staff Member', max_length=100),
        ),
    ]
