# Generated by Django 3.0.8 on 2024-08-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchstock', '0002_auto_20240811_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_id', models.CharField(max_length=10)),
                ('common_name', models.CharField(max_length=50)),
                ('systematic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.IntegerField(default=0)),
                ('institute_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=10)),
                ('lab_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_level_id', models.IntegerField(default=0)),
                ('storage_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(default=0)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='userRole',
            field=models.CharField(choices=[('Stock Manager', 'Stock Manager'), ('Research Staff Member', 'Research Staff Member'), ('Order Manager', 'Order Manager'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Higher Approver', 'Higher Approver')], default='Research Staff Member', max_length=100),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location_id', models.CharField(max_length=10)),
                ('storage_location_name', models.CharField(max_length=50)),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchstock.Laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category_id', models.IntegerField(default=0)),
                ('risk_category', models.CharField(max_length=20)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchstock.StorageLevel')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=10)),
                ('center_name', models.CharField(max_length=100)),
                ('institute_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchstock.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_amount', models.IntegerField(default=1)),
                ('chemical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchstock.Chemical')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchstock.ResearchCenter'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='risk_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchstock.RiskCategory'),
        ),
    ]
